### ISSUE TITLE
validate:"required"是不是无效

### ISSUE THREAD

**Issue by yanghuanxin** [dangerous1990/protoc-plugins#1]
`message Minority{
    // 少数民族信息名称
    string Name =3 [(gogoproto.jsontag) = 'name',(gogoproto.moretags)='gorm:"column:CH_NAME",validate:"required"'];
    // 所属组织REF
    int64 orgRef =4 [(gogoproto.jsontag) = 'orgRef',(gogoproto.moretags)='gorm:"column:I_ORG_REF",validate:"required"'];
}`
validate:"required"没有正确生成
`"properties": {
                "id": {
                    "type": "integer",
                    "description": "唯一标识"
                },
                "name": {
                    "type": "string",
                    "description": "少数民族信息名称"
                },
                "orgRef": {
                    "type": "integer",
                    "description": "所属组织REF"
                },
                "orgName": {
                    "type": "string",
                    "description": "所属组织名称"
                },
                "nationNumber": {
                    "type": "integer",
                    "description": "少数民族成分数量"
                }
}`

**Comment by dangerous1990** [comment]
done
